model_list:
  - model_name: mistral-8x7b
    litellm_params:
      model: openai/mixtral-8x7b-instruct-v0.1-gptq
      api_base: {{RUNPOD_URL}}
      api_key: dummy
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: {{OPENAI_KEY}}

general_settings:
  master_key: dummy-master-key
