from tau2.utils.utils import DATA_DIR

EDUCATION_DATA_DIR = DATA_DIR / "tau2" / "domains" / "education"
EDUCATION_DB_PATH = EDUCATION_DATA_DIR / "db.json"
EDUCATION_POLICY_PATH = EDUCATION_DATA_DIR / "policy.md"
EDUCATION_USER_POLICY_PATH = EDUCATION_DATA_DIR / "user_policy.md"
EDUCATION_TASK_SET_PATH = EDUCATION_DATA_DIR / "tasks.json"

__all__ = [
    "EDUCATION_DATA_DIR",
    "EDUCATION_DB_PATH",
    "EDUCATION_POLICY_PATH",
    "EDUCATION_USER_POLICY_PATH",
    "EDUCATION_TASK_SET_PATH",
]

